# Имя сценария (отображается при запуске)
- name: Настройка SSH доступа для пользователя pss
  hosts: all
  # Выполнять задачи с правами суперпользователя (sudo)
  become: yes

  tasks:
    - name: Установка публичного ключа и создание необходимых директорий
      # Используем официальный модуль для работы с ключами
      ansible.posix.authorized_key:
        # Имя пользователя, в чью домашнюю директорию попадет ключ
        user: pss
        # Состояние "present" означает: "добавить, если ключа нет"
        state: present
        # Сам публичный ключ (строка должна быть в кавычках)
        key: "ssh-rsa AAA***t0= pss@astra"
        # Автоматически создать папку .ssh и установить верные права (0700)
        manage_dir: yes
        # Если файл authorized_keys не существует, он будет создан с правами 0600
