---                     #Начинается всегда с трех тире
- name: test-playbook   #Имя playbook (любое)
  hosts: servers        #Группа хостов, на которых будет происходить выполнение (своя группа, all, ungroupt, localhost)
  become: true          #Запускать все задачи с правами суперпользователя (true или false, по умолчанию - false)
  gather_facts: true    #Осуществлять или нет сбор фактов (данных об управляемых хостах) (true или false, по умолчанию - true)
  vars:                 #Список переменных для этого сценария
    owner: root
    custom_var: 42
  vars_files:           #Файлы с переменными
    - vars.yaml

  tasks:                          #Список задач
    - name: block examples tasks  #Объединенный блок нескольких задач, для которого можно задать условие, теги и.т.д.
      block: 
        - name: Установка apache в centos
          yum:
            name: httpd
            update_cache: true
            state: present

        - name: Запуск apache в centos
          service:
            name: httpd
            state: started
            enabled: true
      tags: tag1, tag2                      #Теги
      when: ansible_os_family == "RedHat"   #Условие выполнения

    - name: Создание файла              #Имя задачи
      file:                             #Модуль
        dest: /var/www/html/index.html  #Аргументы
        state: touch
        owner: "{{ owner }}"            #Использование переменной, всегда выделяется кавычками
        group: "{{ owner }}"
        mode: 0644
      tags: tag1, tag2
      notify: Restart httpd             #Вызывается handlers только если произошли изменения

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
