- name: Опрос версии ОС на всех устройствах
  hosts: 192.168.101.40
  tasks:
    - name: Выводим информацию о ПК
      debug:
        msg: "{{ ansible_default_ipv4.address }} - {{ ansible_hostname }} - {{ ansible_lsb.description }}"
