- name: Установка микросервисов
  hosts: my_hosts
  become: yes
  become_user: root
  become_method: sudo
  tasks:

  - name: apt update
    ansible.builtin.shell: apt update
    ignore_errors: yes

  - name: install zabbix
    ansible.builtin.shell: apt install zabbix-agent2 -y
    ignore_errors: yes

  - name: Удаляем конфигурационный файл zabbix
    ansible.builtin.shell: sudo rm -f /etc/zabbix/zabbix_agent2.conf
    ignore_errors: yes

  - name: copy file conf
    copy:
      src: ./zabbix_agent2.conf
      dest: /etc/zabbix/
      mode: 0644

  - name: restart zabbix
    ansible.builtin.shell: systemctl restart zabbix-agent2.service
    ignore_errors: yes