- name: Установка zabbix-agent2
  hosts: "{{ ip }}"
  become: true
  become_user: root
  become_method: sudo
  tasks:

  - name: apt update
    ansible.builtin.shell: sudo apt update
    ignore_errors: yes

  - name: install zabbix
    ansible.builtin.shell: sudo apt install zabbix-agent2 -y
    ignore_errors: yes

  - name: Удаляем конфигурационный файл zabbix
    ansible.builtin.shell: sudo rm -f /etc/zabbix/zabbix_agent2.conf
    ignore_errors: yes

  - name: Скачать conf файл с GitHub и сохранить в нужную директорию
    get_url:
      url: https://raw.githubusercontent.com/pelts2002/ansible/refs/heads/main/zabbix_agent2.conf
      dest: /etc/zabbix/zabbix_agent2.conf
      mode: '0644'

  - name: меняем hostname в .conf файле
    ansible.builtin.shell: echo "Hostname={{ ip }}" | sudo tee -a /etc/zabbix/zabbix_agent2.conf > /dev/null
    ignore_errors: yes

  - name: restart zabbix
    ansible.builtin.shell: sudo systemctl restart zabbix-agent2.service
    ignore_errors: yes
