- name: Установка zabbix-agent2
  hosts: "{{ ip }}"
  become: true
  become_user: root
  become_method: sudo
  tasks:

  - name: Производим "apt install zabbix-agent"
    ansible.builtin.shell: sudo apt install zabbix-agent

  - name: Удаляем конфигурационный файл zabbix
    ansible.builtin.shell: sudo rm -f /etc/zabbix/zabbix_agentd.conf

  - name: Скачать conf файл с GitHub и сохранить в нужную директорию
    ansible.builtin.shell: sudo wget -O /etc/zabbix/zabbix_agentd.conf https://raw.githubusercontent.com/pelts2002/ansible/refs/heads/main/zabbix_agent2.conf

  - name: меняем hostname в .conf файле
    ansible.builtin.shell: echo "Hostname={{ ip }}" | sudo tee -a /etc/zabbix/zabbix_agentd.conf > /dev/null

  - name: restart zabbix
    ansible.builtin.shell: sudo systemctl restart zabbix-agent
    ignore_errors: yes

  - name: enable zabbix
    ansible.builtin.shell: sudo systemctl enable zabbix-agent
    ignore_errors: yes
