- name: Установка микросервисов
  hosts: my_hosts
  become: yes
  become_user: root
  become_method: sudo
  tasks:

  - name: apt update
    ansible.builtin.shell: sudo apt update
    ignore_errors: yes

  - name: install zabbix
    ansible.builtin.shell: sudo apt install zabbix-agent2 -y
    ignore_errors: yes

  - name: Удаляем конфигурационный файл zabbix
    ansible.builtin.shell: sudo rm -f /etc/zabbix/zabbix_agent2.conf
    ignore_errors: yes

  - name: Копируем файл в директорию /etc/zabbix
    ansible.builtin.shell: cd /etc/zabbix && sudo wget https://github.com/pelts2002/ansible/blob/main/zabbix_agent2.conf
    ignore_errors: yes

  - name: restart zabbix
    ansible.builtin.shell: systemctl restart zabbix-agent2.service
    ignore_errors: yes
