- name: Лицензии
  hosts: "{{ target_host }}"
  tasks:

  - name: Copy lic in srv
    copy:
      # Откуда брать файл
      src: "/opt/Lic/ViPNet/ГБУЗ ПК Чайковская ЦГБ {{ name_dir_lic }}/ГБУЗ ПК Чайковская ЦГБ {{ name_dir_lic }}/{{ name_lic }}"
      # Куда файл доставить
      dest: "/srv/{{ name_lic }}"
