- name: Опрос версии ОС на всех устройствах
  hosts: all
  tasks:
    - name: Выводим информацию о ПК
      command: df -h
      register: peremennaya
      debug:
        msg1: "{{ ansible_hostname }} - {{ ansible_default_ipv4.address }} - {{ ansible_lsb.description }}"
        msg2: peremennaya.stdout_lines
