- name: Опрос версии ОС на всех устройствах
  hosts: all
  tasks:
    - name: Запуск команды df -h
      command: df -h
      register: peremennaya

    - name: Выводим информацию о ПК
      debug:
        msg1: "{{ ansible_hostname }} - {{ ansible_default_ipv4.address }} - {{ ansible_lsb.description }}"
        msg2: var=peremennaya.stdout_lines
