- name: Опрос версии ОС на всех устройствах
  hosts: all
  tasks:
    - name: Выводим информацию о ПК
      debug:
        msg: "{{ ansible_hostname }} - {{ ansible_default_ipv4.address }} - {{ ansible_lsb.description }}"
