- name: Опрос версии ОС на всех устройствах
  hosts: all
  tasks:
    - name: Получаем версию ОС
      shell: cat /etc/os-release | grep '^PRETTY_NAME' | cut -d '"' -f 2
      register: os_version
      changed_when: false

    - name: Получаем имя ПК
      shell: hostname
      register: name_pc
      changed_when: false

    - name: Выводим информацию о ПК
      debug:
        msg: "{{ name_pc.stdout }} - {{ inventory_hostname }} - {{ os_version.stdout }}"
