- name: Опрос версии ОС на всех устройствах
  hosts: all
  tasks:
    - name: Запуск команды df -h
      command: df -h
      register: peremennaya

    - name: Выводим информацию о ПК
      debug:
        msg: >
          Хост: {{ ansible_hostname }}\n
          IP: {{ ansible_default_ipv4.address }}
          Описание ОС: {{ ansible_lsb.description }}
          Вывод df -h:
          {{ peremennaya.stdout_lines | join('\n') }}
