# - name: Опрос версии ОС на всех устройствах
# hosts: all
#  tasks:
#    - name: Выводим информацию о ПК
#      debug:
#        msg: "{{ ansible_default_ipv4.address }} - {{ ansible_hostname }} - {{ ansible_lsb.description }}"
# dpkg -l | grep cprocsp

- name: Установка КриптоПро
  hosts: all
  become: yes

  tasks:
    - name: Смотрим ОС
      ansible.builtin.shell: cat /etc/os-release | grep '^PRETTY_NAME' | cut -d '"' -f 2
      register: os_pretty_name

    - name: Установка КриптоПро на Red OS
      shell: 
      when: "'RED OS MUROM (7.3.4)' in os_pretty_name.stdout"

    - name: Установка КриптоПро на Astra Linux
      shell: |
        cd /srv
        tar -zxf linux-amd64_deb.tgz
        cd /srv/linux-amd64_deb
        ./install.sh
      when: "'Astra Linux' in os_pretty_name.stdout"

    - name: Установка КриптоПро на Alt Workspace
      shell: |
        apt-get install cryptopro-preinstall -y
        cd /srv
        tar -xf linux-amd64.tgz
        cd /srv/linux-amd64
        apt-get install cprocsp-curl* lsb-cprocsp-base* lsb-cprocsp-capilite* lsb-cprocsp-kc1-64* lsb-cprocsp-rdr-64* -y
        apt-get install cprocsp-cptools* -y
        wget -P /home/user/Рабочий\ стол/ https://raw.githubusercontent.com/pelts2002/ansible/main/cptools.desktop
      when: "'ALT Workstation 10.2 (Autolycus)' in os_pretty_name.stdout"
