- name: Опрос версии ОС на всех устройствах
  hosts: all
  tasks:
    - name:
      command: df -h
      register: peremennaya
    
    - name: Выводим информацию о ПК
      debug:
        msg: "{{ ansible_hostname }} - {{ ansible_default_ipv4.address }} - {{ ansible_lsb.description }} - {{ peremennaya.stdout_lines }}"
