- hosts: 192.168.101.54
  gather_facts: no
  tasks:

  - name: copy file Рабочий стол    
    ignore_errors: yes
    copy:
      src: /opt/ya_ereisz.desktop
      dest: /home/user/Рабочий стол/Лекарства.desktop
      owner: user
      group: users
      mode: 0744
      force: yes

  - name: copy file Desktop    
    ignore_errors: yes
    copy:
      src: /opt/ya_ereisz.desktop
      dest: /home/user/Desktop/Лекарства.desktop
      owner: user
      group: users
      mode: 0744
      force: yes
